#!/bin/sh
#########
# sysman
#
# Author: Ryan Flett - s3633011
# Date written: 29-9-2016
# Date last modified: 3-10-2016
#
# This provides an interface to easily access functions from the basic, advanced, and userman scripts.
#
# Users are prompted with a menu and interact by entering the appropriate number. 
# The number is read and either a new menu will be displayed or the corresponding script 
# will be run. Options are read using a case switch.
# In some cases more user input is required (such as the backup, and user information).
#
#########

# DISPLAYS THE MAIN MENU
showMainMenu() {
	clear
	printf "##################################\n\n"
	echo "    Welcome to System Manager"
	printf "   ---------------------------\n\n"
	printf "    Please select a menu item:\n\n"
	echo "    1) Basic menu options"
	echo "    2) Advanced menu options"
	echo "    3) Passwd file options"
	printf "    4) Quit\n\n"
   echo "##################################"

	readMainMenuOptions
}

# DISPLAYS THE BASIC MENU
showBasicMenu() {
	clear
	printf "#################################################\n\n"
	echo "               Basic Tasks Menu"
	printf "    ------------------------------------------\n\n"
	echo "     1) Show free memory"
	echo "     2) Show free disk space"
	echo "     3) Show disk quota"
	echo "     4) Show the groups I am a member of"
	echo "     5) Show the history of commands for bash"
	printf "     6) Quit this menu\n\n"
   echo "#################################################"

	# READ MENU CHOICE
	readBasicOptions
}

# DISPLAYS THE ADVANCED MENU
showAdvancedMenu() {
	clear
	printf "####################################################################\n\n"
	echo "                         Advanced Tasks Menu"
	printf "   -------------------------------------------------------------\n\n"
	echo "    1) Print the number of CPUs available on the system"
	echo "    2) Print the maximum number of open files allowed per user"
	echo "    3) Backup all files that match a criterion"
	printf "    4) Quit this menu\n\n"
   echo "####################################################################"
	
	# READ MENU CHOICE
	readAdvancedOptions
}

# DISPLAYS THE PASSWD MENU
showPasswdMenu() {
	clear
	printf "########################################################\n\n"
	echo "                  Passwd Tasks Menu"
	printf "   --------------------------------------------------\n\n"
	echo "    1) Print the userid of a specified user"
	echo "    2) Print the groupid of a specified user"
	echo "    3) Print the comment field for a specified user"
	echo "    4) Print the home directory of a specified user"
	echo "    5) Print the default shell of a specified user"
	printf "    6) Quit this menu\n\n"
   echo "########################################################"
	
	# READ MENU CHOICE
	readPasswdOptions
}

# READS THE MENU CHOICE FROM THE USER FOR THE MAIN MENU
readMainMenuOptions() {
	read -r -p "Please enter your choice [1-4]: " choice

	echo ""

	# EXECUTE APPROPRIATE SCRIPT OR FUNCTION FOR THE MENU OPTION
	case $choice in
		1) showBasicMenu ;;
		2) showAdvancedMenu ;;
		3) showPasswdMenu ;;
		4) 
			clear
			exit 0
			;;
		*) echo "Invalid choice..." && sleep 1
			readMainMenuOptions
	esac
}

# READS THE MENU CHOICE FROM THE USER FOR THE BASIC MENU
readBasicOptions() {	
	echo ""

	read -r -p "Please enter your choice [1-6]: " choice

	# EXECUTE APPROPRIATE SCRIPT OR FUNCTION FOR THE MENU OPTION
	case $choice in
		1) ./basic freemem ;;
		2) ./basic diskfree ;;
		3) ./basic quota ;;
		4) ./basic groups ;;
		5) ./basic history ;;
		6) showMainMenu ;;
		*) echo "Invalid choice..." && sleep 1
			readBasicOptions
	esac

	# READ MENU CHOICE
	readBasicOptions
}

# READS THE MENU CHOICE FROM THE USER FOR THE ADVANCED MENU
readAdvancedOptions() {
	echo ""	

	read -r -p "Please enter your choice [1-4]: " choice

	# TAKES THE BACKUP ARGUMENTS FROM THE USER AND SENDS THEM TO BACKUP SCRIPT
	runBackup() {
		read -r -p "Please enter wildcard and destination or c to cancel eg: \\*.txt my-text-files : " backupSettings
	
		# RETURN TO MENU IF CANCELLED OR NO ARGUMENTS GIVEN
		if [ -z "$backupSettings" ] || [ "$backupSettings" = "c" ]; then
			readAdvancedOptions
		else
			wildcard=$(echo "$backupSettings" | cut -d ' ' -f1)
			dest=$(echo "$backupSettings" | cut -d ' ' -f2)

			./advanced -b "$wildcard" "$dest"
		fi
	}

	# EXECUTE APPROPRIATE SCRIPT OR FUNCTION FOR THE MENU OPTION
	case $choice in
		1) ./advanced -p ;;
		2) ./advanced -o ;;
		3) runBackup ;;
		4) showMainMenu ;;
		*) echo "Invalid choice..." && sleep 1
			readAdvancedOptions
	esac

	# READ MENU CHOICE
	readAdvancedOptions
}

# READ THE MENU CHOICE FROM THE USER FOR THE PASSWD MENU
readPasswdOptions() {	
	echo ""

	read -r -p "Please enter your choice [1-6]: " choice

	# READS USER NAME FROM INPUT
	readUser() {	
		read -r -p "Please enter the user: " user
	}

	# EXECUTE APPROPRIATE SCRIPT OR FUNCTION FOR THE MENU OPTION
	case $choice in
		1) 
			readUser
			./userman userid "$user"
			;;
		2) 
			readUser
			./userman groupid "$user"
			;;
		3) 
			readUser
			./userman comment "$user" 
			;;
		4) 
			readUser
			./userman home "$user" 	
			;;
		5) 
			readUser
			./userman shell "$user" 
			;;
		6) showMainMenu ;;
		*) echo "Invalid choice..." && sleep 1
			readPasswdOptions
	esac

	# READ MENU CHOICE
	readPasswdOptions
}

#############################################
# SHOW THE MAIN MENU WHEN THE SCRIPT IS RUN #
#############################################
while true; do
	showMainMenu
done

